title: tumin.
description: portfolio sitede
baseurl: ""  # For GitHub Pages projects, use: "/repositoryname"
url: ""      # Your domain or username.github.io

markdown: kramdown
kramdown:
  syntax_highlighter: coderay

plugins:
  - jekyll-feed

github_username: tumaro
twitter_username: tumaro1001
email: contact.tumins@gmail.com
